version: '3.8'

services:
    planify-back:
        image: kreyzix/planify-back:${VERSION}
        build: .
        ports:
            - "5000:5000"
        restart: always
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - CDN_URL=${CDN_URL}
            - CDN_STORAGE_ZONE=${CDN_STORAGE_ZONE}
            - CDN_STORAGE_PATH=${CDN_STORAGE_PATH}
            - CDN_ACCESS_KEY=${CDN_ACCESS_KEY}

