version: '3.8'

services:
    # planify-back:
    #     build: .
    #     ports:
    #         - "8090:8090"
    #     links:
    #         - planify-db
    planify-db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: POSTGRES_PASSWORD

