version: '3.8'

services:
    planify-back:
        image: kreyzix/planify-back:${VERSION}
        build: .
        ports:
            - "${APP_PORT}:${APP_PORT}"
        restart: always
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - CDN_URL=${CDN_URL}
            - CDN_STORAGE_ZONE=${CDN_STORAGE_ZONE}
            - CDN_STORAGE_PATH=${CDN_STORAGE_PATH}
            - CDN_ACCESS_KEY=${CDN_ACCESS_KEY}
            - GMAPS_API_KEY=${GMAPS_API_KEY}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - APP_PORT=${APP_PORT}
            - APP_URL="${APP_URL}:${APP_PORT}"

