---
- hosts: dev_server
  tasks:
    # - name: get env vars
    #   ansible.builtin.debug:
    #     msg: "{{ lookup('env', item) }}"
    #   loop:
    #     - DATABASE_URL
    #     - CDN_URL
    #     - CDN_STORAGE_ZONE
    #     - CDN_STORAGE_PATH
    #     - CDN_ACCESS_KEY

    # - name: Pull code from github
    #   ansible.builtin.git:
    #     repo: 'git@github.com:jrivo/planify-back.git'
    #     dest: ~/planify-back
    #     version: "{{ lookup('env', 'BRANCH') }}"
    #     clone: true
    #     update: true

    # - name: Enter in app & pull new image
    #   become: true
    #   shell: 'cd planify-back && docker compose pull'

    - name: Inject env variables
      become: true
      environment:
        DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
        CDN_URL: "{{ lookup('env', 'CDN_URL') }}"
        CDN_STORAGE_ZONE: "{{ lookup('env', 'CDN_STORAGE_ZONE') }}"
        CDN_STORAGE_PATH: "{{ lookup('env', 'CDN_STORAGE_PATH') }}"
        CDN_ACCESS_KEY: "{{ lookup('env', 'CDN_ACCESS_KEY') }}"
      shell: 'export DATABASE_URL=$DATABASE_URL && export CDN_URL=$CDN_URL && export CDN_STORAGE_ZONE=$CDN_STORAGE_ZONE && export CDN_STORAGE_PATH=$CDN_STORAGE_PATH && export CDN_ACCESS_KEY=$CDN_ACCESS_KEY'

    - name: Check env variables
      become: true
      shell: 'echo $DATABASE_URL && echo $CDN_URL && echo $CDN_STORAGE_ZONE && echo $CDN_STORAGE_PATH && echo $CDN_ACCESS_KEY'
      register: env_vars

    - debug:
        var: env_vars.stdout_lines

    # - name: get DB URL
    #   ansible.builtin.debug:
    #     msg: "{{ lookup('env', 'DATABASE_URL') }}"

    # - name: Run new image
    #   become: true
    #   shell: 'cd planify-back && docker compose up -d'